package com.jumbo.tools.input;

public enum JumboKey {
	NONE, ESCAPE, ONE, TWO, THREE, FOUR, FIVE, SIX, SEVEN, EIGHT, NINE, ZERO, MINUS, EQUALS, BACK, TAB, Q, W, E, R, T, Y, U, I, O, P, LBRACKET, RBRACKET, RETURN, LCONTROL, A, S, D, F, G, H, J, K, L, SEMICOLON, APOSTROPHE, GRAVE, LSHIFT, BACKSLASH, Z, X, C, V, B, N, M, COMMA, PERIOD, SLASH, RSHIFT, MULTIPLY, LMENU, SPACE, CAPSLOCK, F1, F2, F3, F4, F5, F6, F7, F8, F9, F10, NUMLOCK, SCROLL, NUMPAD7, NUMPAD8, NUMPAD9, SUBTRACT, NUMPAD4, NUMPAD5, NUMPAD6, ADD, NUMPAD1, NUMPAD2, NUMPAD3, NUMPAD0, DECIMAL, F11, F12, F13, F14, F15, F16, F17, F18, KANA, F19, CONVERT, NOCONVERT, YEN, NUMPADEQUALS, CIRCUMFLEX, AT, COLON, UNDERLINE, KANJI, STOP, AX, UNLABELED, NUMPADENTER, RCONTROL, SECTION, NUMPADCOMMA, DIVIDE, SYSRQ, RMENU, FUNCTION, PAUSE, HOME, UP, PAGEUP, LEFT, RIGHT, END, DOWN, PAGEDOWN, INSERT, LMETA, RMETA, APPS, POWER, SLEEP;

	boolean down = false;
}
